name: CI/CD - Build, Push, Deploy to EC2

on:
  push:
    branches: [main]
  pull_request:
    types: [closed]

env:
  IMAGE: ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app

jobs:
  build-push-deploy:
    if: >
      github.event_name == 'push'
      || (github.event_name == 'pull_request' && github.event.pull_request.merged == true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image (from my-devops-app/Dockerfile)
        run: |
          docker build -f my-devops-app/Dockerfile \
            -t $IMAGE:latest \
            -t $IMAGE:${{ github.sha }} \
            my-devops-app

      - name: Push images to Docker Hub
        run: |
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

      - name: Deploy to EC2 via SSH
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          port: ${{ secrets.EC2_SSH_PORT || '22' }}
          script: |
            set -e
            echo "Logging into Docker Hub on EC2..."
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

            echo "Attempting to free port 80 if occupied by a container..."
            # find any container publishing host port 80 and remove it
            holder=$(docker ps --format '{{.ID}} {{.Names}} {{.Ports}}' | grep '0.0.0.0:80' | awk '{print $1}' || true)
            if [ -n "$holder" ]; then
              echo "Found container using port 80: $holder — removing it"
              docker rm -f "$holder" || true
            fi

            # If a host process (nginx/apache) listens on port 80, try to stop it (needs sudo)
            if sudo ss -ltnp | grep -q ':80'; then
              echo "Port 80 is used by a host process. Trying to stop nginx/apache..."
              sudo systemctl stop nginx || sudo systemctl stop apache2 || echo "No nginx/apache found or sudo failed"
            fi

            echo "Pulling image..."
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest

            echo "Starting container (publishing host port 80 -> container 80)..."
            # remove any previous container with our name then start new one
            docker rm -f my-devops-app || true
            docker run -d --name my-devops-app --restart unless-stopped -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/my-devops-app:latest

            sleep 2
            echo "Deployment complete. Running containers:"
            docker ps --filter "name=my-devops-app"
