name: React App CI/CD

on:
  push:
    branches:
      - main   # jab main branch pe push ho to chale
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        

      - name: Build Docker image
        run: docker build -t react-app .

    
